apiVersion: v1
kind: Service
metadata:
  name: openmetadata-airflow
  namespace: daap-dev
spec:
  selector:
    app: openmetadata-ingestion-airflow
  ports:
    - name: http
      port: 8080
      targetPort: 8080