openmetadata-ingestion:
  enabled: true

  image:
    repository: openmetadata/ingestion
    tag: 1.11.2
    pullPolicy: IfNotPresent

  env:
    - name: OPENMETADATA_SERVER_HOST
      value: openmetadata
    - name: OPENMETADATA_SERVER_PORT
      value: "8585"