source:
  type: snowflake
  serviceName: Snowflake-Daap

  serviceConnection:
    config:
      type: Snowflake
      username: <user>
      password: ${SNOWFLAKE_PASSWORD}
      account: <account>
      warehouse: <warehouse>
      role: <role>
      database: <ONE_DATABASE>

      accountUsageSchema: SNOWFLAKE.ACCOUNT_USAGE
      queryTag: openmetadata

  sourceConfig:
    config:
      type: DatabaseQueryUsage
      queryLogDuration: 1

sink:
  type: metadata-rest
  config: {}

workflowConfig:
  openMetadataServerConfig:
    hostPort: http://openmetadata:8585/api
    authProvider: openmetadata
    securityConfig:
      jwtToken: ${OPENMETADATA_JWT_TOKEN}
