source:
  type: snowflake
  serviceName: Snowflake-Daap

  sourceConfig:
    config:
      type: AutoClassification
      
processor:
  type: orm-profiler
  config: {}

sink:
  type: metadata-rest
  config: {}

workflowConfig:
  loggerLevel: INFO
  openMetadataServerConfig:
    hostPort: http://openmetadata.daap-dev.svc.cluster.local:8585/api
    authProvider: openmetadata
    securityConfig:
      jwtToken: ${OPENMETADATA_JWT_TOKEN}
