apiVersion: batch/v1
kind: CronJob
metadata:
  name: snowflake-profiler
  namespace: daap-dev
spec:
  schedule: "0 4 * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3

  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: profiler
              image: openmetadata/ingestion:1.11.3
              command: ["metadata"]
              args:
                - ingest
                - -c
                - /configs/snowflake-profiler.yaml
              env:
                - name: SNOWFLAKE_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: snowflake-secrets
                      key: password
                - name: OPENMETADATA_JWT_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: openmetadata-bot
                      key: jwt
              volumeMounts:
                - name: config
                  mountPath: /configs

          volumes:
            - name: config
              configMap:
                name: snowflake-profiler-classification-config

          restartPolicy: Never
