source:
  type: snowflake
  serviceName: Snowflake-Daap

  serviceConnection:
    config:
      type: Snowflake
      username: ANILJITH.SATHYANATHAN@TSWORKS.IO
      password: ${SNOWFLAKE_PASSWORD}
      account: A6050728655071-TSWORKZ_PARTNER
      warehouse: COMPUTE_WH
      role: DAAP_DEVELOPER_ROLE

      databaseFilterPattern:
        includes:
          - ^DAAP_DB$

  sourceConfig:
    config:
      type: DatabaseMetadata
      includeTables: true
      includeViews: true
      includeTags: true
      includeOwners: true

workflowConfig:
  loggerLevel: INFO

  openMetadataServerConfig:
    hostPort: http://openmetadata.daap-dev.svc.cluster.local:8585/api
    authProvider: openmetadata
    securityConfig:
      jwtToken: ${OPENMETADATA_JWT_TOKEN}