source:
  type: snowflake
  serviceName: Snowflake-Daap

  serviceConnection:
    config:
      type: Snowflake
      username: ANILJITH.SATHYANATHAN@TSWORKS.IO
      password: ${SNOWFLAKE_PASSWORD}
      account: A6050728655071-TSWORKZ_PARTNER
      warehouse: COMPUTE_WH
      role: DAAP_DEVELOPER_ROLE

      accountUsageSchema: SNOWFLAKE.ACCOUNT_USAGE
      queryTag: openmetadata

  sourceConfig:
    config:
      type: DatabaseLineage

sink:
  type: metadata-rest
  config: {}

workflowConfig:
  openMetadataServerConfig:
    hostPort: http://openmetadata:8585/api
    authProvider: openmetadata
    securityConfig:
      jwtToken: ${OPENMETADATA_JWT_TOKEN}
