name: Deploy OpenMetadata Stack to AKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set AKS Context
        uses: azure/aks-set-context@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          resource-group: ${{ secrets.AKS_RESOURCE_GROUP }}
          cluster-name: ${{ secrets.AKS_CLUSTER_NAME }}

      - name: Login to Azure Container Registry
        uses: docker/login-action@v2
        with:
          registry: daappoc25.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
        
      - name: Build & Push OpenMetadata Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile-openmetadata
          push: true
          tags: daappoc25.azurecr.io/openmetadata:latest

      - name: Build & Push Airflow Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile-openmetadata
          push: true
          tags: daappoc25.azurecr.io/airflow:latest

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
            version: v3.18.0

      - name: Add Helm Repositories
        run: |
          helm repo add open-metadata https://helm.open-metadata.org
          helm repo add opensearch https://opensearch-project.github.io/helm-charts
          helm repo add apache-airflow https://airflow.apache.org
          helm repo update
                            

      - name: Deploy OpenSearch
        run: |
          kubectl apply -f charts/openmetadata/opensearch-sysctl-daemonset.yaml
          helm upgrade --install opensearch opensearch/opensearch \
            --namespace daap-dev \
            -f charts/openmetadata/values-opensearch.yaml

      - name: Deploy OpenMetadata
        run: |
          helm upgrade --install openmetadata open-metadata/openmetadata \
            --namespace daap-dev \
            -f charts/openmetadata/values.yaml \
            --timeout 15m

      - name: Deploy Airflow
        run: |
          kubectl apply -f charts/openmetadata/airflow-pvc.yaml
          helm upgrade --install airflow \
            https://github.com/apache/airflow/releases/download/helm-chart%2F1.13.1/airflow-1.13.1.tgz \
            --namespace daap-dev \
            --version 1.13.1 \
            -f charts/openmetadata/airflow-config.yaml \
            --timeout 15m
          kubectl patch deployment airflow-webserver \
            -n daap-dev \
            --type=json \
            -p='[
              {
                "op": "remove",
                "path": "/spec/template/spec/containers/0/startupProbe"
              }
            ]'