name: Deploy OpenMetadata Stack to AKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS Context
        uses: azure/aks-set-context@v1
        with:
          resource-group: ${{ secrets.AKS_RESOURCE_GROUP }}
          cluster-name: ${{ secrets.AKS_CLUSTER_NAME }}

      - name: Login to Azure Container Registry
        uses: docker/login-action@v2
        with:
          registry: daappoc25.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
        
      - name: Build & Push OpenMetadata Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile-openmetadata
          push: true
          tags: daappoc25.azurecr.io/openmetadata:latest


      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Add Helm Repositories
        run: |
          helm repo add open-metadata https://helm.open-metadata.org
          helm repo add opensearch https://opensearch-project.github.io/helm-charts
          helm repo add apache-airflow https://airflow.apache.org
          helm repo update

      - name: Deploy OpenSearch
        run: |
          helm upgrade --install opensearch opensearch/opensearch \
            --namespace daap-dev \
            -f charts/openmetadata/values.yaml

      - name: Deploy Airflow
        run: |
          helm upgrade --install airflow apache-airflow/airflow \
            --namespace daap-dev \
            --set images.airflow.repository=apache/airflow \
            --set images.airflow.tag=2.9.1 \
            --set webserver.service.type=LoadBalancer \
            --set "workers.persistence.enabled=true" \
            --set "workers.persistence.size=1Gi" \
            --set "triggerer.persistence.enabled=true" \
            --set "triggerer.persistence.size=1Gi" \
            -f charts/openmetadata/values.yaml


      - name: Deploy OpenMetadata
        run: |
          helm upgrade --install openmetadata open-metadata/openmetadata \
            --namespace daap-dev \
            -f charts/openmetadata/values.yaml \
            --timeout 10m0s
